# Задание №5
### Метод вращения для поиска собственных значений матрицы

In [1]:
import pandas as pd
import numpy as np
from math import atan, sin, cos

In [2]:
matrix = np.array([[1, 2, -4],
                  [2, 3, 4],
                  [-4, 4, 5]]) #Начальный массив

e = 0.0001 #Минимальное значение элементов, вне главной диаганали

In [3]:
def find_degree(aij, aii, ajj):
    return (atan((2 * aij)/(aii - ajj)))/2     

In [4]:
def create_matrix_deegree(degree, shape):
    row = shape[0]
    column = shape[1]
    
    matrix_degree = np.array([[cos(degree), -sin(degree)],
                             [sin(degree),  cos(degree)]])
    e_matrix = np.eye(3)
    
    e_matrix[row][row] = matrix_degree[0][0]
    e_matrix[column][column] = matrix_degree[1][1]
    e_matrix[row][column] = matrix_degree[0][1]
    e_matrix[column][row] = matrix_degree[1][0]

    return e_matrix

In [5]:
i,j = np.indices(matrix.shape)
def create_copy(past_arr):
    copy_matrix = matrix.copy()
    copy_matrix[copy_matrix < 0] *= -1
    copy_matrix[i == j] = 0
    
    
    return copy_matrix

In [6]:
copy_matrix = create_copy(matrix)


while copy_matrix.max() > e:
    ind = np.unravel_index(np.argmax(copy_matrix), copy_matrix.shape)
    degree = find_degree(matrix[ind[0]][ind[1]], matrix[ind[0]][ind[0]], matrix[ind[1]][ind[1]],)
    
    deg_arr = create_matrix_deegree(degree, ind)
    matrix = np.dot(np.dot(deg_arr.transpose(), matrix), deg_arr)
    copy_matrix = create_copy(matrix)
    
    print(f'\n{matrix}\n')


[[-1.47213595e+00  3.80422607e+00 -3.15458600e-16]
 [ 3.80422607e+00  3.00000000e+00  2.35114101e+00]
 [-3.50025531e-17  2.35114101e+00  7.47213595e+00]]


[[-3.64879230e+00 -1.11068736e-16 -1.16762992e+00]
 [-3.99890760e-17  5.17665635e+00  2.04071174e+00]
 [-1.16762992e+00  2.04071174e+00  7.47213595e+00]]


[[-3.64879230e+00  5.89503293e-01 -1.00789161e+00]
 [ 5.89503293e-01  3.98306937e+00 -1.68495910e-16]
 [-1.00789161e+00  8.39348521e-18  8.66572293e+00]]


[[-3.73073871e+00  5.87564454e-01  1.77742891e-17]
 [ 5.87564454e-01  3.98306937e+00 -4.77717997e-02]
 [ 2.66554158e-16 -4.77717997e-02  8.74766934e+00]]


[[-3.77523708e+00  6.46092316e-17  3.60759918e-03]
 [-1.50501384e-17  4.02756774e+00 -4.76353868e-02]
 [ 3.60759918e-03 -4.76353868e-02  8.74766934e+00]]


[[-3.77523708e+00  3.64024231e-05  3.60741552e-03]
 [ 3.64024231e-05  4.02708705e+00  1.64087020e-17]
 [ 3.60741552e-03  2.07756065e-16  8.74815002e+00]]


[[-3.77523812e+00  3.64024216e-05 -2.36369042e-16]
 [ 3.6402421

#### Результат

In [7]:
matrix[i!=j] = 0
print(matrix)

[[-3.77523812  0.          0.        ]
 [ 0.          4.02708705  0.        ]
 [ 0.          0.          8.74815106]]
