# Задание №5
### Метод вращения для поиска собственных значений матрицы

In [1]:
import pandas as pd
import numpy as np
from math import atan, sin, cos

In [2]:
matrix = np.array([[1, 2, 5],
                  [2, 3, 4],
                  [5, 4, 5]]) #Начальный массив

e = 0.0001 #Минимальное значение элементов, вне главной диаганали

In [3]:
def find_degree(aij, aii, ajj):
    return (atan((2 * aij)/(aii - ajj)))/2     

In [4]:
def create_matrix_deegree(degree, shape):
    row = shape[0]
    column = shape[1]
    
    matrix_degree = np.array([[cos(degree), -sin(degree)],
                             [sin(degree),  cos(degree)]])
    e_matrix = np.eye(3)
    
    e_matrix[row][row] = matrix_degree[0][0]
    e_matrix[column][column] = matrix_degree[1][1]
    e_matrix[row][column] = matrix_degree[0][1]
    e_matrix[column][row] = matrix_degree[1][0]

    return e_matrix

In [5]:
i,j = np.indices(matrix.shape)
def create_copy(past_arr):
    copy_matrix = matrix.copy()
    copy_matrix[copy_matrix < 0] *= -1
    copy_matrix[i == j] = 0
    
    
    return copy_matrix

In [6]:
copy_matrix = create_copy(matrix)


while copy_matrix.max() > e:
    ind = np.unravel_index(np.argmax(copy_matrix), copy_matrix.shape)
    degree = find_degree(matrix[ind[0]][ind[1]], matrix[ind[0]][ind[0]], matrix[ind[1]][ind[1]],)
    
    deg_arr = create_matrix_deegree(degree, ind)
    matrix = np.dot(np.dot(deg_arr.transpose(), matrix), deg_arr)
    copy_matrix = create_copy(matrix)
    
    print(f'\n{matrix}\n')


[[-2.38516481e+00 -5.86380776e-01  3.92867726e-16]
 [-5.86380776e-01  3.00000000e+00  4.43352654e+00]
 [ 7.63135010e-16  4.43352654e+00  8.38516481e+00]]\т

[[-2.38516481e+00 -5.11041965e-01 -2.87538737e-01]
 [-5.11041965e-01  5.05467831e-01 -1.68358563e-16]
 [-2.87538737e-01 -3.93006099e-16  1.08796970e+01]]\т

[[-2.47285310e+00  1.19949737e-17 -2.83397085e-01]
 [-2.25882280e-17  5.93156128e-01  4.86273327e-02]
 [-2.83397085e-01  4.86273327e-02  1.08796970e+01]]\т

[[-2.47886527e+00  1.03137928e-03 -7.55989016e-17]
 [ 1.03137928e-03  5.93156128e-01  4.86163937e-02]
 [ 2.67481240e-16  4.86163937e-02  1.08857091e+01]]\т

[[-2.47886527e+00  1.03136777e-03  4.87150884e-06]
 [ 1.03136777e-03  5.92926496e-01  1.38936813e-19]
 [ 4.87150884e-06 -2.71984813e-16  1.08859388e+01]]\т

[[-2.47886562e+00  6.28832255e-21  4.87150856e-06]
 [-3.05454402e-17  5.92926842e-01  1.63563052e-09]
 [ 4.87150857e-06  1.63563025e-09  1.08859388e+01]]\т


#### Результат

In [9]:
matrix[i!=j] = 0
print(matrix)

[[-2.47886562  0.          0.        ]
 [ 0.          0.59292684  0.        ]
 [ 0.          0.         10.88593877]]
